---

- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - { role: deploy_app }

  post_tasks:
  - name: Cleaning up the workdir
    file:
      path: "{{ workdir_path }}"
      state: absent

...
