---

version: '3'

services:
  {{ nginx_service }}:
    image: {{ app_img }}:{{ release_version }}
    ports:
      - 8080
    environment:
      - SERVICE_PORTS=8080
    deploy:
      replicas: {{ replicas_quantity }}
      update_config:
        parallelism: {{ parallelism_rate }}
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 60s
    networks:
      - web

  ha_proxy:
    image: {{ haproxy_img }}
    depends_on:
      - {{ nginx_service }}
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay

...
